# Generated by Django 5.1.5 on 2025-01-21 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0002_initial_investment_plans'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usdtwallet',
            options={'verbose_name': 'Portefeuille USDT', 'verbose_name_plural': 'Portefeuilles USDT'},
        ),
        migrations.AlterField(
            model_name='usdtwallet',
            name='address',
            field=models.CharField(blank=True, max_length=42, unique=True),
        ),
    ]
