# Generated by Django 5.1.5 on 2025-01-22 19:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0004_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentplan',
            name='maximum_investment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
