# Generated by Django 5.1.5 on 2025-01-22 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0005_investmentplan_maximum_investment'),
    ]

    operations = [
        migrations.AddField(
            model_name='usdttransaction',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usdttransaction',
            name='transaction_type',
            field=models.CharField(choices=[('DEPOSIT', 'Deposit'), ('INVESTMENT', 'Investment'), ('WITHDRAWAL', 'Withdrawal'), ('EARNINGS', 'Earnings'), ('REFERRAL_BONUS', 'Referral Bonus'), ('INVESTMENT_UPGRADE', 'Investment Upgrade')], max_length=20),
        ),
    ]
